server:
  port: 8761

spring:
  application:
    name: nacos-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


logging:
  pattern:
    console: "%red(%date{dd HH:mm:ss.SSS}) %green([%thread]) %highlight(%-5level) %cyan([%logger{36}:%-4.4line]) - %boldMagenta(%msg%n)"

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

debug: false
